/*
    GooeyFiWidgetFactory.cpp
    
MIT License

Copyright (c) 2016 cbtek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
//----------------------------------------
//GooeyFiWidgetFactory.cpp generated by CBTek Solutions on 02-17-2017 at 06:28:11 PM
//----------------------------------------

#include "GooeyFiWidgetFactory.h"
#include "GooeyFiNumeric.h"
#include "GooeyFiButton.h"
#include "GooeyFiTextInput.h"
#include "GooeyFiPathBrowser.h"

#include "utility/inc/StringUtils.hpp"
#include "utility/inc/Exception.hpp"

using namespace cbtek::common::utility;

namespace cbtek {
namespace products {
namespace gooeyfi {
namespace core {

CREATE_EXCEPTION_NO_MSG(InvalidGooeyFiWidgetException)

GooeyFiWidgetPtr GooeyFiWidgetFactory::create(const std::string& commaSeperatedNameValuePairParams)
{

    //read all name-value pairs into nameValueMap
    std::vector<std::string> pairs;
    std::map<std::string, std::string> nameValueMap;
    pairs = StringUtils::split(commaSeperatedNameValuePairParams, ",");
    if (pairs.size() > 0)
    {
        for (const auto& pair : pairs)
        {
            std::vector<std::string> nameValuePair = StringUtils::split(pair,":");
            StringUtils::clean(nameValuePair);
            if (nameValuePair.size() > 1)
            {
                std::string name = StringUtils::toUpperTrimmed(nameValuePair[0]);
                std::string value = nameValuePair[1];
                nameValueMap[name]=value;
            }
        }
    }

    std::string typeValue = StringUtils::toUpperTrimmed(nameValueMap["TYPE"]);
    std::string subType = StringUtils::toUpperTrimmed(nameValueMap["STYLE"]);

    if (typeValue == "TEXTINPUT")
    {
        GooeyFiTextInput widget;
        widget.setLabel(nameValueMap["LABEL"]);
        widget.setId(nameValueMap["ID"]);
        if (subType == "MULTI")
        {
            widget.setType(GooeyFiTextInputType::MultiLine);
        }
        else widget.setType(GooeyFiTextInputType::SingleLine);
        widget.setText(nameValueMap["value"]);
        return GooeyFiWidgetPtr(new GooeyFiTextInput(widget));
    }
    else if (typeValue == "NUMERIC")
    {
        GooeyFiNumeric widget;
        widget.setLabel(nameValueMap["LABEL"]);
        widget.setId(nameValueMap["ID"]);
        if (subType == "FLOAT")
        {
            widget.setType(GooeyFiNumericType::Float);
        }
        else widget.setType(GooeyFiNumericType::Integer);
        widget.setIncrement(StringUtils::toFloat64(nameValueMap["increment"]));
        widget.setMin(StringUtils::toFloat64(nameValueMap["min"]));
        widget.setMax(StringUtils::toFloat64(nameValueMap["max"]));
        widget.setValue(StringUtils::toFloat64(nameValueMap["value"]));
        return GooeyFiWidgetPtr(new GooeyFiNumeric(widget));
    }
    else if (typeValue == "BUTTON")
    {
        GooeyFiButton widget;
        widget.setLabel(nameValueMap["LABEL"]);
        widget.setId(nameValueMap["ID"]);
        if (subType == "ACTION")
        {
            widget.setType(GooeyFiButtonType::Action);
        }
        else if (subType == "CHECKBOX")
        {
            widget.setType(GooeyFiButtonType::Checkbox);
        }
        else widget.setType(GooeyFiButtonType::Radio);
        return GooeyFiWidgetPtr(new GooeyFiButton(widget));
    }
    else if (typeValue == "PATHBROWSER")
    {
        GooeyFiPathBrowser widget;
        widget.setLabel(nameValueMap["LABEL"]);
        widget.setId(nameValueMap["ID"]);
        if (subType == "FILE")
        {
            widget.setType(GooeyFiPathBrowserType::File);
        }
        else widget.setType(GooeyFiPathBrowserType::Folder);
        return GooeyFiWidgetPtr(new GooeyFiPathBrowser(widget));
    }

    throw InvalidGooeyFiWidgetException(EXCEPTION_TAG_LINE+"Could not detect widget type from data sent in.  Data="+commaSeperatedNameValuePairParams);
}


}}}}//end namespace


