/*
    GooeyFiPathBrowser.cpp
    
MIT License

Copyright (c) 2016 cbtek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
//----------------------------------------
//GooeyFiPathBrowser.cpp generated by CBTek Solutions on 02-17-2017 at 06:10:25 PM
//----------------------------------------
#include "GooeyFiPathBrowser.h"

namespace cbtek {
namespace products {
namespace gooeyfi {
namespace core {

inline static std::string getPathBrowserTypeStr(GooeyFiPathBrowserType type)
{
    if (type == GooeyFiPathBrowserType::File)
    {
        return "FILE";
    }
    else return "FOLDER";
}

GooeyFiPathBrowser::GooeyFiPathBrowser()
{

}

GooeyFiPathBrowser::~GooeyFiPathBrowser()
{

}

void GooeyFiPathBrowser::setType(const GooeyFiPathBrowserType & value)
{
    m_type=value;
}

void GooeyFiPathBrowser::setPathValue(const std::string & value)
{
    m_pathValue=value;
}

void GooeyFiPathBrowser::setBrowseButtonLabel(const std::string & value)
{
    m_browseButtonLabel=value;
}

const GooeyFiPathBrowserType &GooeyFiPathBrowser::getType() const
{
    return m_type;
}

const std::string &GooeyFiPathBrowser::getPathValue() const
{
    return m_pathValue;
}

const std::string &GooeyFiPathBrowser::getBrowseButtonLabel() const
{
    return m_browseButtonLabel;
}

GooeyFiWidgetType GooeyFiPathBrowser::getWidgetType() const
{
    return GooeyFiWidgetType::PathBrowser;
}

void GooeyFiPathBrowser::write(common::utility::XMLStreamWriter &xml)
{
    xml.writeAttribute("value",m_pathValue);
    xml.writeAttribute("style",getPathBrowserTypeStr(m_type));
}


}}}}//end namespace


