/**
MIT License

Copyright (c) 2016 cbtek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
//----------------------------------------
//XMLStreamWriter.cpp generated by cberry on 06-29-2015 at 11:47:28 PM
//----------------------------------------

#include "XMLStreamWriter.h"

namespace cbtek {
namespace common {
namespace utility {


XMLStreamWriter::XMLStreamWriter(std::ostream &out)
    : m_out(out)
{
    m_currentTab = 0;
}

void XMLStreamWriter::writeStartDocument(const std::string &version, bool flag)
{
    m_out << "<?xml version=\""<<version<<"\" encoding=\"UTF-8\" standalone=\""<<(flag?"yes":"no")<<"\"?>"<<std::endl;
}

void XMLStreamWriter::writeStartElementNoAttributes(const std::string &tag)
{
    writeTabs();
    m_out <<"<"<<tag<<">\n";
    m_currentTab++;
}

void XMLStreamWriter::writeStartElement(const std::string &tag)
{
    writeTabs();
    m_out <<"<"<<tag;
    m_currentTab++;
}

void XMLStreamWriter::writeEndElement()
{
     m_out<<"/>"<<std::endl;
     if (m_currentTab > 0)
     {
         m_currentTab--;
     }
}

void XMLStreamWriter::writeEndElement(const std::string &tag)
{
    if (m_currentTab > 0)
    {
        m_currentTab--;
    }
    writeTabs();
    m_out<<"</"<<tag<<">"<<std::endl;
}

void XMLStreamWriter::writeTextElement(const std::string &tag, const std::string &text)
{
    writeTabs();
    m_out<<"<"<<tag<<">"<<text<<"</"<<tag<<">"<<std::endl;

}


void XMLStreamWriter::writeAttribute(const std::string &attributeName, const std::string &attributeValue)
{
    m_out<<" "<<attributeName<<"=\""<<attributeValue<<"\"";
}

XMLStreamWriter::~XMLStreamWriter()
{

}

void XMLStreamWriter::writeTabs()
{
    for (size_t a1 = 0;a1<m_currentTab;++a1)
    {
        m_out << "    ";
    }
}
}}}//end namespace


